#+TITLE: mpisee: a profiling tool for MPI communicators
#+OPTIONS: ^:nil num:nil

* Introduction
=mpisee= is a profiling tool for MPI that provides profiling data for the communicators of the MPI applications. To conveniently read the output of =mpisee= use =mpisee-through= script to post-processes the output file for quick summary information.
* Features
The tool provides the following data:
- For each communicator:
  - For each MPI call
    1. Time spent
    2. Volume
    3. Number of calls
- Additional data:
  1. Total time of every MPI rank
  2. Node mapping of every MPI rank
- Output in a csv file
- Post-processing with =mpisee-through=
* Build
1. ~CC=mpicc make~ to compile the profiling library, the shared object will be created in ~./lib~ folder.
** Dependencies
1. MPI library (openmpi, mpich) version $> 2$
2. gcc version that supports lto, otherwise disable lto flag in Makefile
*IMPORTANT*: Make sure that the application is compiled with the same MPI library as mpisee
* Usage
- Recommended: ~LD_PRELOAD=/path/to/mpisee/lib/libmpisee.so run <application>~
- You can also link your application with the =libmpisee.so= using the ~-L/path/to/mpisee/lib~ and ~-lmpisee~
  - To run with this add the ~/path/to/mpisee/lib~ to LD_LIBRARY_PATH
* Output
** Quick summary
To get a quick summary of the profile:
~python mpisee-through.py <args> <output file>~
- Explain args here
- =mpisee= output example
#+begin_src latex
\begin{figure}[!t]
  \centering
\begin{lstlisting}[basicstyle=\tiny\tt,framesep=0pt,framexleftmargin=2pt,xleftmargin=0pt]
COMM                SIZE      PROCS
W_a1_s2.0           128       0-127

	Call                   Mean[s]    Min[s]    Max[s]         Volume    #Calls
	---------------------------------------------------------------------------
	Alltoallv               0.8016    0.3520    1.1856     3873236800     11776


COMM                SIZE      PROCS
W_a1_s3.0           128       0-63, 128-191

	Call                   Mean[s]    Min[s]    Max[s]         Volume    #Calls
	---------------------------------------------------------------------------
	Alltoallv               1.1803    0.5428    1.8756     7456121600     11776


COMM                SIZE      PROCS
W_a1_s4.0           4         0, 64, 128, 192

	Call                   Mean[s]    Min[s]    Max[s]         Volume    #Calls
	---------------------------------------------------------------------------
	Alltoallv               0.1416    0.0020    0.2715        2980800       368


COMM                SIZE      PROCS
W_a1_s5.0           256       0-255

	Call                   Mean[s]    Min[s]    Max[s]         Volume    #Calls
	---------------------------------------------------------------------------
	Alltoallv               1.0335    0.7398    1.4108     8740110400     23552
\end{lstlisting}
\caption{A subset of the communicator-centric output produced by
  \mpiseesummary for \splatt.}
  \label{fig:splatt_with_mpisee_summary}
\end{figure}
#+end_src
** Profiler output file description
- The output csv file consists of lines that start with '#', with '#@', and the rest of the data that start with the MPI rank number.
- Lines that start with '#' contain metadata information such as:
  - Profile start date
  - Profile end date
  - MPI library version
  - Application and arguments
  - =mpisee= version
  - =mpisee= environment vars
- Lines that start with '#@' contain information of how to read the data lines and some data information:
  - =#@mapping_l= Mapping of each process
  - =#@metric_l= denotes the type of metric used for the specific line ("VOL, TIME, NCALLS")
  - =#@metric_type_l= denotes the unit for this metric (float,int)
  - =#@comm_l= list of communicator names
  - =#@comm_sz_l= list of communicator sizes
  - =#@call_l= list of MPI calls
  - =#@rank_start_l= list of start timestamp for each rank
  - =#@rank_end_l= list of end timestamp for each rank
- Format of a data line:
  "Rank", "Comm", "Call", "Type", "Val"
  - Rank: the corresponding MPI ranks
  - Call: index to the MPI call list
  - Comm: index to the communicator list
  - Type: index to type of metric used
  - Val: index to unit of metric
